name: news_app_clean_architecture
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.10.4

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  ionicons: ^0.2.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  intl: ^0.18.1
  
  # Database
  floor: ^1.4.2  

  # Networking
  dio: ^5.3.0    
  retrofit: ^4.0.1 

  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  flutter_hooks: ^0.20.5
  cached_network_image: ^3.3.1
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.6
  
  retrofit_generator: ^7.0.8 
  
  floor_generator: ^1.4.2
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - .env
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300